export const SOCKETS_CONNECTING = "SOCKETS_CONNECTING";
export const SOCKETS_CONNECT = "SOCKETS_CONNECT";
export const SOCKETS_CONNECTED = "SOCKETS_CONNECTED";
export const SOCKETS_DISCONNECTING = "SOCKETS_DISCONNECTING";
export const SOCKETS_DISCONNECT = "SOCKETS_DISCONNECT";
export const SOCKETS_DISCONNECTED = "SOCKETS_DISCONNECTED";