export const MESSAGE_SENDING = "MESSAGE_SENDING";
export const MESSAGE_SEND = "MESSAGE_SEND";
export const MESSAGE_INCOMING = "MESSAGE_INCOMING";
export const MESSAGE_RECEIVING = "MESSAGE_RECEIVING";
export const MESSAGE_RECEIVE = "MESSAGE_RECEIVE";
export const MESSAGE_SUBSCRIBE = "MESSAGE_SUBSCRIBE";
export const SETUP_CHAT_BOX = "SETUP_CHAT_BOX";